#     _    _              _ _                   _  #
#    / \  | | ____ _ _ __(_) |    _____   _____| | #
#   / _ \ | |/ / _` | '__| | |   / _ \ \ / / _ \ | #
#  / ___ \|   < (_| | |  | | |__|  __/\ V /  __/ | #
# /_/   \_\_|\_\__,_|_|  |_|_____\___| \_/ \___|_| #

#############################################
#       ExperienceMultiplier  Config       #
#############################################

double_exp_on_command: true
